name: Deploy Application
on: 
  push:
    branches:
      - master

jobs:
  create-deployment-artifacts:
    name: Create deployment artifacts
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - name: Compile css & javascript
        run: 
          npm install
          npm run prod
      
      - name: Configure PHP 7.4
        uses: shivammathur/setup-php@master
        with: 
          php-version: 7.4
          extensions: mbstring, ctype, fileinfo, openssl, PDO, bcmath, json, tokenizer, xml, intl

      - name: Install Composer Dependencies
        run: 
          composer install --no-dev --no-interaction --prefer-dist
